apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nfd-manager
subjects:
- kind: ServiceAccount
  name: nfd-manager
  namespace: openshift-nfd
